title: Awesome Blog
author: Saheb Preet Singh
email: saheb.preet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome blog

# social links
twitter_username: sahebpreet_ # DO NOT include the @ character, or else the build will fail!
github_username:  sahebpreet # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
